data:
  dir: '/mnt/nasl2/observed_weather'
  final_data: 'data'
  solar_dir: 'data/solar'
  wind_dir: 'data/wind'
  from_date: '2023-07-24'
  hist_date: '2023-12-31'
  turbine_dir: "power_curves"
  turbine_data: 'turbine_power.csv'
  specs_path: "turbine_specs.csv"
  cp_data: "turbine_cp.csv"
  ct_data: "turbine_ct.csv"
  sleep: 0.25
  
scraping:
  download_url: 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/10_minutes/'
  vars: ['air_temperature', 'solar', 'wind_test']
  sleep: 1
  get_historical: True
  get_recent: True


write:
  recent_pkl: 'recent_dfs.pkl'
  historical_pkl: 'historical_dfs.pkl'
  master_pkl: 'master_data.pkl'
  create_table: True
  write_historical: True
  write_recent: True
  write: True
  threshold: 0.001
  db_conf: 
    host: 'localhost'
    database: 'Observations'
    user: 'postgres'
    passw: ''
  
synth:
  pressure: 
    param: 'PP_10'
    name: 'Pressure'
    unit: 'Pa'
  temperature: 
    param: 'TT_10'
    name: 'Temperature at 2m'
    unit: '°C'
  relhum: 
    param: 'RF_10'
    name: 'Relative Humidity'
    unit: '%'
  dewpoint: 
    param: 'TD_10'
    name: 'Dew Point'
    unit: '°C'
  dhi: 
    param: 'DS_10'
    name: 'DHI'
    unit: 'W/m$^2$'
  ghi: 
    param: 'GS_10'
    name: 'GHI'
    unit: 'W/m$^2$'
  v_wind: 
    param: 'FF_10'
    name: 'Wind Speed'
    unit: 'm/s'
  d_wind: 
    param: 'DD_10'
    name: 'Wind Direction'
    unit: '°'
  prec:
    param: 'RWS_10'
    name: 'Precipitation Rate'
    unit: 'mm'
  sigma_wind_lat: 
    param: 'SLA_10'
    name: 'Standard Deviation of Zonal Wind Speed'
    unit: ''
  sigma_wind_lon: 
    param: 'SLO_10'
    name: 'Standard Deviation of Meridional Wind Speed'
    unit: ''
  w_wind: 
    param: 'W_Wind'
    name: 'Vertical Wind Speed'
    unit: 'm/s'
  latitude: 
    param: 'geoBreite'
    name: 'Latitude'
    unit: '°'
  longitude: 
    param: 'geoLaenge'
    name: 'Longitude'
    unit: '°'
  elevation: 
    param: 'Stationshoehe'
    name: 'Station Height'
    unit: 'm'
  density: 
    param: 'rho'
    name: 'Density'
    unit: 'kg/m$^3$'
  sat_vap_pressure:
    param: 'p_s'
    name: 'Saturated Vapor Pressure'
    unit: 'Pa'
  sat_vap_pressure_hub:
    param: 'p_s_hub'
    name: 'Saturated Vapor Pressure at Hub Height'
    unit: 'Pa'
  v_wind_hub: 
    param: 'v_wind_hub'
    name: 'Wind Speed at Hub Height'
    unit: 'm/s'
  pressure_hub: 
    param: 'p_hub'
    name: 'Pressure at Hub Height'
    unit: 'Pa'
  temperature_hub: 
    param: 't_hub'
    name: 'Temperature at Hub Height'
    unit: '°C'
  density_hub: 
    param: 'rho_hub'
    name: 'Density at Hub Height'
    unit: 'kg/m$^3$'
  C_p:
    param: 'C_p'
    name: 'Cps of Cp Curve'
    unit: '-'

  
adjustable_pv_params:
  installed_power: 100
  surface_tilt: 40
  surface_azimuth: 245
  gamma_pdc: -0.0035
  albedo: 0.25
  eta_inv_nom: 0.96
  eta_inv_ref: 0.9637

adjustable_wind_params:
  turbine: 'FWT 120/3000'
  installed_power: 100
  h1: 10
  h2: 100 
  #rated_power: 10000
  Cp: 0.59
  #rotor_diameter: 60
  cut_in_speed: 3
  rated_speed: 12.5
  cut_out_speed: 15
  p_s_model: 'huang'
  v2_method: 'seven_power'
  karman: 0.4
  temp_gradient: 0.00649

logging:
  verbose: False
  log_file_write: 'write_db.log'
  datefmt: '%Y-%m-%d %H:%M:%S'