data:
  dir: 'data'
  final_data: 'data/final'
  sleep: 0.25
  
scraping:
  download_url: 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/10_minutes/'
  vars: ['air_temperature', 'solar', 'wind']
  sleep: 1

write:
  write: True
  db_conf: 
    host: 'localhost'
    database: 'WeatherForecasts'
    #user: 'name',
    #passw: 'passw'
  
synth:
  pressure: 
    param: 'PP_10'
    name: 'Pressure'
    unit: 'Pa'
  temperature: 
    param: 'TT_10'
    name: 'Pressure'
    unit: '°C'
  relhum: 
    param: 'RF_10'
    name: 'Relative Humidity'
    unit: '%'
  dewpoint: 
    param: 'TD_10'
    name: 'Dew Point'
    unit: '°C'
  dhi: 
    param: 'DS_10'
    name: 'DHI'
    unit: 'W/m$^2$'
  ghi: 
    param: 'GS_10'
    name: 'GHI'
    unit: 'W/m$^2$'
  v_wind: 
    param: 'FF_10'
    name: 'Wind Speed'
    unit: 'm/s'
  d_wind: 
    param: 'DD_10'
    name: 'Wind Direction'
    unit: '°'
  latitude: 
    param: 'geoBreite'
    name: 'Latitude'
    unit: '°'
  longitude: 
    param: 'geoLaenge'
    name: 'Longitude'
    unit: '°'
  elevation: 
    param: 'Stationshoehe'
    name: 'Station Height'
    unit: 'm'
  density: 
    param: 'rho'
    name: 'Density'
    unit: 'kg/m$^3$'

logging:
  verbose: False
  log_file_write: 'write_db.log'
  datefmt: '%Y-%m-%d %H:%M:%S'