data:
  dir: '/mnt/nasl2/observed_weather'
  synth_dir: 'data/synthetic'
  raw_dir: 'data/raw'
  w_vert_dir: 'data/vertical_wind'
  from_date: '2023-07-24'
  hist_date: '2023-12-31'
  turbine_dir: "power_curves"
  turbine_power: 'turbine_power.csv'
  turbine_specs: "turbine_specs.csv"
  turbine_cp: "turbine_cp.csv"
  turbine_ct: "turbine_ct.csv"
  turbine_names: "turbine_names.csv"
  hor_vars: ['aswdifd_s', 'aswdir_s', 'alb_rad', 'clct', 't_2m', 'relhum_2m', 'td_2m', 'h_snow', 'rho_snow', 'prr_gsp', 'prs_gsp', 'prg_gsp', 't_g', 'u_10m', 'v_10m']
  vert_vars: ['u_wind', 'v_wind', 'temperature', 'pressure', 'relhum']
  sleep: 0.25

scraping:
  download_url: 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/10_minutes/'
  vars: ['air_temperature', 'wind_test', 'solar', 'precipitation']
  sleep: 1
  get_historical: True
  get_recent: True
  overwrite: True


write:
  recent_pkl: 'recent_dfs.pkl'
  historical_pkl: 'historical_dfs.pkl'
  master_pkl: 'master_data.pkl'
  create_table: False
  write_historical: True
  write_recent: True
  write_master: True
  write: True
  threshold: 0.001
  clean_pv: False
  clean_wind: True
  get_vertical_wind: False
  db_conf:
    host: 'localhost'
    database: ''
    database_obs: 'Observations'
    database_frcst: 'WeatherDB'
    port: 5432
    user: 'postgres'
    passw: ''
    do_update: False # on conflict do what?

synth:
  pressure:
    param: 'PP_10'
    name: 'Pressure'
    unit: 'Pa'
  temperature:
    param: 'TT_10'
    name: 'Temperature at 2m'
    unit: '°C'
  relhum:
    param: 'RF_10'
    name: 'Relative Humidity'
    unit: '%'
  dewpoint:
    param: 'TD_10'
    name: 'Dew Point'
    unit: '°C'
  dhi:
    param: 'DS_10'
    name: 'DHI'
    unit: 'W/m$^2$'
  ghi:
    param: 'GS_10'
    name: 'GHI'
    unit: 'W/m$^2$'
  v_wind:
    param: 'FF_10'
    name: 'Wind Speed'
    unit: 'm/s'
  d_wind:
    param: 'DD_10'
    name: 'Wind Direction'
    unit: '°'
  prec:
    param: 'RWS_10'
    name: 'Precipitation Rate'
    unit: 'mm'
  prec_dau:
    param: 'RWS_DAU_10'
    name: 'Precipitation duration'
    unit: 'min'
  sigma_wind_lat:
    param: 'SLA_10'
    name: 'Standard Deviation of Zonal Wind Speed'
    unit: ''
  sigma_wind_lon:
    param: 'SLO_10'
    name: 'Standard Deviation of Meridional Wind Speed'
    unit: ''
  w_wind:
    param: 'W_Wind'
    name: 'Vertical Wind Speed'
    unit: 'm/s'
  latitude:
    param: 'geoBreite'
    name: 'Latitude'
    unit: '°'
  longitude:
    param: 'geoLaenge'
    name: 'Longitude'
    unit: '°'
  elevation:
    param: 'Stationshoehe'
    name: 'Station Height'
    unit: 'm'
  density:
    param: 'rho'
    name: 'Density'
    unit: 'kg/m$^3$'
  sat_vap_pressure:
    param: 'p_s'
    name: 'Saturated Vapor Pressure'
    unit: 'Pa'
  sat_vap_pressure_hub:
    param: 'p_s_hub'
    name: 'Saturated Vapor Pressure at Hub Height'
    unit: 'Pa'
  v_wind_hub:
    param: 'v_wind_hub'
    name: 'Wind Speed at Hub Height'
    unit: 'm/s'
  v_wind_vert:
    param: 'w_vert'
    name: 'Vertical Wind Speed at Ground Level'
    unit: 'm/s'
  pressure_hub:
    param: 'p_hub'
    name: 'Pressure at Hub Height'
    unit: 'Pa'
  temperature_hub:
    param: 't_hub'
    name: 'Temperature at Hub Height'
    unit: '°C'
  density_hub:
    param: 'rho_hub'
    name: 'Density at Hub Height'
    unit: 'kg/m$^3$'
  cp_curve:
    param: 'Cp'
    name: 'Cps of Cp Curve'
    unit: '-'
  power_curve:
    param: 'power_curve'
    name: 'Theoretical power according to power curve'
    unit: 'Watt'
  power:
    param: 'power'
    name: 'Calculated power'
    unit: 'Watt'


adjustable_pv_params:
  installed_power: 100
  surface_tilt: 40
  surface_azimuth: 245
  gamma_pdc: -0.0035
  albedo: 0.25
  eta_inv_nom: 0.96
  eta_inv_ref: 0.9637

adjustable_wind_params:
  turbines: ['Enercon E-70 E4 2.300',
             'Enercon E-82 E2 2.000',
             'Enercon E-115 2.500',
             'Vestas V90',
             'Vestas V112-3.45',
             'Vestas V80-1.8']
  hub_heights: [57,138,149,95,119,78]
  h1: 10
  rated_speed: ''
  p_s_model: 'huang'
  v2_method: 'alphaI'
  karman: 0.4
  temp_gradient: 0.00649
  interpol_method: 'polynomial'
  polynom_grad: 2
  noise: 0.075
  mean_age_years: 15
  std_dev_age_years: 5
  annual_degradation: 0.0063

logging:
  verbose: False
  log_file_write: 'write_db.log'
  datefmt: '%Y-%m-%d %H:%M:%S'