data:
  downloads_dir: 'data'
  final_data: 'data/final'
  sleep: 0.25
  
scraping:
  download_url: 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/10_minutes/'
  vars: ['air_temperature', 'solar', 'wind']
  sleep: 1

write:
  write: True
  db_conf: 
    host: 'localhost'
    database: 'WeatherForecasts'
    #user: 'name',
    #passw: 'passw'
  
synth:
  param_pressure: 'PP_10'
  param_temperature: 'TT_10'
  param_relhum: 'RF_10'
  param_dewpoint: 'TD_10'
  param_dhi: 'DS_10'
  param_ghi: 'GS_10'
  param_v_wind: 'FF_10'
  param_d_wind: 'DD_10'
  param_latitude: 'geoBreite'
  param_longitude: 'geoLaenge'
  param_elevation: 'Stationshoehe'

logging:
  verbose: False
  log_file_write: 'write_db.log'
  datefmt: '%Y-%m-%d %H:%M:%S'