data:
  dir: '/mnt/nas/observed_weather'
  synth_dir: '/mnt/nas/synthetic/open-meteo/icon_d2'
  master_dir: '/mnt/nas/synthetic'
  raw_dir: '/mnt/nas/open-meteo/wind/icon_d2'
  raw_data_timestamp_col: 'date'
  pkl_dir: 'data/pkl_files'
  re_ninja_dir: 'data/renewables.ninja'
  w_vert_dir: 'data/vertical_wind'
  from_date: '2023-07-24'
  hist_date: '2023-12-31'
  turbine_dir: "power_curves"
  turbine_power: 'turbine_power.csv'
  turbine_specs: "turbine_specs.csv"
  turbine_cp: "turbine_cp.csv"
  turbine_ct: "turbine_ct.csv"
  turbine_names: "turbine_names.csv"
  wind_ages: 'data/wind_ages.npy'
  pv_ages: 'data/pv_ages.npy'
  hor_vars: ['aswdifd_s', 'aswdir_s', 'alb_rad', 'clct', 't_2m', 'relhum_2m', 'td_2m', 'h_snow', 'rho_snow', 'prr_gsp', 'prs_gsp', 'prg_gsp', 't_g', 'u_10m', 'v_10m']
  vert_vars: ['u_wind', 'v_wind', 'temperature', 'pressure', 'relhum']
  sleep: 0.25

scraping:
  download_url: 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/10_minutes/'
  vars: ['air_temperature', 'wind_test', 'solar', 'precipitation']
  sleep: 1
  get_historical: True
  get_recent: True
  overwrite: True


write:
  recent_pkl: 'recent_dfs.pkl'
  historical_pkl: 'historical_dfs.pkl'
  master_pkl: 'master_data.pkl'
  create_table: False
  write_historical: True
  write_recent: True
  write_master: False
  write: True
  threshold: 0.008 # 0.8 % missing values
  clean_pv: True
  clean_wind: False
  db_conf:
    host: 'localhost'
    database: 'WeatherDB'
    port: 5432
    user: 'postgres'
    passw: ''
    do_update: True # on conflict do update?


wind_params:
  turbines: ['Enercon E-70 E4 2.300',
             'Enercon E-82 E2 2.000',
             'Enercon E-115 2.500',
             'Vestas V90',
             'Vestas V112-3.45',
             'Vestas V80-1.8']
  hub_heights: [57,138,149,95,119,78]
  nwp_heights: [10,80,120,180]
  h1: 10
  p_s_model: 'huang'
  v2_method: 'alphaI'
  karman: 0.4
  temp_gradient: 0.00649
  noise: 0.0
  annual_degradation: 0.0063
  apply_ageing: True
  hourly_resolution: True
  random_seed: 42

logging:
  verbose: False
  log_file_write: 'write_db.log'
  datefmt: '%Y-%m-%d %H:%M:%S'

features:
  pressure:
    name: 'surface_pressure'
    unit: 'hPa'
  temperature:
    name: 'temperature_2m'
    unit: '°C'
  relhum:
    name: 'relative_humidity_2m'
    unit: ''
  dewpoint:
    name: 'dew_point'
    unit: '°C'
  dhi:
    name: 'dhi'
    unit: 'W/m$^2$'
  dni:
    name: 'dni'
    unit: 'W/m$^2$'
  ghi:
    name: 'ghi'
    unit: 'W/m$^2$'
  wind_speed_hub:
    name: 'wind_speed'
    unit: 'm/s'
  wind_speed_10:
    name: 'wind_speed_10m'
    unit: 'm/s'
  wind_speed_80:
    name: 'wind_speed_80m'
    unit: 'm/s'
  wind_speed_120:
    name: 'wind_speed_120m'
    unit: 'm/s'
  wind_speed_180:
    name: 'wind_speed_180m'
    unit: 'm/s'
  d_wind_80:
    name: 'wind_direction_80m'
    unit: '°'
  d_wind_120:
    name: 'wind_direction_120m'
    unit: '°'
  d_wind_180:
    name: 'wind_direction_180m'
    unit: '°'
  alpha:
    name: 'hellmann_coefficient'
    unit: ''
  latitude:
    name: 'latitude'
    unit: '°'
  longitude:
    name: 'longitude'
    unit: '°'
  elevation:
    name: 'station_height'
    unit: 'm'
  density:
    name: 'density'
    unit: 'kg/m$^3$'
  sat_vap_pressure:
    name: 'saturated_vapor_pressure'
    unit: 'Pa'
  sat_vap_pressure_hub:
    name: 'saturated_vapor_pressure'
    unit: 'Pa'
  wind_speed_hub:
    name: 'wind_speed'
    unit: 'm/s'
  pressure_hub:
    name: 'pressure'
    unit: 'Pa'
  temperature_hub:
    name: 'temperature'
    unit: '°C'
  density_hub:
    name: 'density'
    unit: 'kg/m$^3$'
  cp_curve:
    name: 'cp'
    unit: '-'
  power_curve:
    name: 'power_curve'
    unit: 'Watt'
  power:
    name: 'power'
    unit: 'Watt'